apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: moviedb
  name: moviedb-persistentvolumeclaim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi