apiVersion: v1
kind: ConfigMap 
metadata:
  name: nginx-configmap
  labels:
    app: nginx
data:
  default.conf: |
    server {
      listen 80;

      location /api/v1/movies {
        proxy_pass http://movieapi-service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://castapi-service:8000/api/v1/casts;
      }

    }