apiVersion: v1
kind: PersistentVolume
metadata:
  name: castdb-persistentvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres_data_cast/"