apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: castdb
  name: castdb-persistentvolumeclaim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi